# Generated by Django 3.2.4 on 2021-06-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Levelname', models.CharField(max_length=300)),
                ('testname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.CharField(max_length=500)),
                ('l2', models.CharField(max_length=500)),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jumpstart.alllevels')),
            ],
        ),
    ]
