# Generated by Django 3.2.4 on 2021-06-06 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Jumpstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='l1',
            new_name='ct',
        ),
        migrations.RemoveField(
            model_name='details',
            name='l2',
        ),
        migrations.AddField(
            model_name='alllevels',
            name='startedfrom',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Started from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='your_choice',
            field=models.BooleanField(default=False),
        ),
    ]
