# Generated by Django 3.2.4 on 2021-06-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jumpstart', '0003_alter_alllevels_startedfrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alllevels',
            name='startedfrom',
        ),
    ]
