# Generated by Django 3.2.4 on 2021-06-07 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Jumpstart', '0004_remove_alllevels_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='alllevels',
            name='startedfrom',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started from'),
            preserve_default=False,
        ),
    ]
