# Generated by Django 3.2.4 on 2021-06-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jumpstart', '0005_alllevels_startedfrom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Level',
            new_name='test',
        ),
    ]
